/*
 * display7SEG.c
 *
 *  Created on: May 28, 2024
 *      Author: Dell
 */

#include "display7SEG.h"
void display7SEG(int k){
	switch (k){
	case 0:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_SET);
			break;
		case 1:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_SET);
	    	HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_SET);
			break;
		case 2:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_RESET);
			break;
		case 3:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_RESET);
			break;
		case 4:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_RESET);
			break;
		case 5:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_RESET);
			break;
		case 6:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_RESET);
			break;
		case 7:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_SET);
			break;
		case 8:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_RESET);
			break;
		case 9:
			HAL_GPIO_WritePin(GPIOA, LED7_0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, LED7_5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, LED7_6_Pin, GPIO_PIN_RESET);
			break;
		default:
			break;
	}
}
